name: emod-demo-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - jupyter
  - jupyterlab
  - notebook
  - matplotlib-base
  - pybind11
  - cmake
  - libboost